---
version: 1

#kind: group
kind: experiment


environment:
  resources:
    gpu:
      requests: 1
      limits: 1


params:
  feature_dim: 32
  relation_dim: 8
  class_num: 5
  sample_num_per_class: 1 #1 #5
  batch_num_per_class: 19 #19 #15
  episode: 500000
  test_episode: 100
  learning_rate: 0.001
  test_interval: 1000
  hidden_unit: 10
  model_name_or_path: "lilingling/fewshot_apt/orimodels/"             #ernie模型路径
  datas_name_or_path: "lilingling/omniglot_resized3/"             #ernie模型路径


build:
  dockerfile: Dockerfile

run:
  cmd:  python3  omniglot/omniglot_train_one_shot.py
                           --feature_dim={{ feature_dim }} \
                           --relation_dim={{ relation_dim }} \
                           --class_num={{ class_num }} \
                           --sample_num_per_class={{ sample_num_per_class }} \
                           --batch_num_per_class={{ batch_num_per_class }} \
                           --episode={{ episode }} \
                           --test_episode={{ test_episode }} \
                           --learning_rate={{ learning_rate }} \
                           --test_interval={{ test_interval }} \
                           --hidden_unit={{ hidden_unit }} \
                           --model_name_or_path={{ model_name_or_path }} \
                           --datas_name_or_path={{ datas_name_or_path }} 
